# Generated by Django 2.2.6 on 2021-08-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_schedule_finish_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="id",
        ),
        migrations.AlterField(
            model_name="schedule",
            name="trace_id",
            field=models.CharField(max_length=33, primary_key=True, serialize=False, verbose_name="trace id"),
        ),
    ]
